openapi: 3.0.0
info:
  title: Ecommerce API
  version: "0.1"
  description: Ecommerce API to manage products
paths:
  /products:
    get:
      tags:
        - products
      operationId: main.get_products
      summary: Get all products
      parameters:
        - $ref: "#/components/parameters/product_type"
        - $ref: "#/components/parameters/limit"
      responses:
        "200":
          $ref: "#/components/responses/ReturnProducts"

        "401":
          $ref: "#/components/responses/UnauthorizedError"
      security:
        - jwt: []
        - api_key: []

  "/products/available":
    get:
      tags:
        - products
      operationId: main.get_available_products
      summary: Get all available products

      responses:
        "200":
          $ref: "#/components/responses/ReturnProducts"

  "/products/{product_id}":
    get:
      tags:
        - products
      operationId: main.get_product
      summary: Get a single product
      parameters:
        - $ref: "#/components/parameters/product_id"
      responses:
        "200":
          description: Return product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: product does not exist
    put:
      tags:
        - products
      operationId: main.put_product
      summary: Update a product
      parameters:
        - $ref: "#/components/parameters/product_id"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: product updated
        "201":
          description: New product created
    delete:
      tags:
        - products
      operationId: main.delete_product
      summary: Delete a product
      parameters:
        - $ref: "#/components/parameters/product_id"
      responses:
        "204":
          description: product was deleted
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          description: product does not exist

  "/products/{product_id}/availability":
    get:
      tags:
        - products
      operationId: main.get_product_availability
      summary: get the availability of a product
      parameters:
        - $ref: '#/components/parameters/product_id'
      responses:
        "200":
          description: product availability
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

        "404":
          description: product does not exist

  "/cart":
    post:
      tags:
        - products
      operationId: main.put_cart
      summary: add a product to cart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        "200":
          description: Cart status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

  "/checkout":
    post:
      tags:
        - products
      operationId: main.get_checkout
      summary: checkout cart
      responses:
        "200":
          description: Checkout status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

  "/user/profile":
    get:
      tags:
        - user
      operationId: main.get_profile
      summary: get user profile
      responses:
        "200":
          description: user profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: user does not exist


  /auth/{user_id}:
    get:
      summary: Return JWT token
      operationId: jwtdecoder.generate_token
      parameters:
        - name: user_id
          description: User unique identifier
          in: path
          required: true
          example: 12
          schema:
            type: integer
      responses:
        "200":
          description: JWT token
          content:
            application/json:
              schema:
                type: object

  /secret:
    get:
      summary: Return secret string
      operationId: jwtdecoder.get_secret
      responses:
        "200":
          description: secret response
          content:
            "text/plain":
              schema:
                type: string
      security:
        - jwt: ["secret"]

  /healthz:
    get:
      operationId: main.health
      summary: Return status of server
      responses:
        "200":
          description: return status

components:
  parameters:
    limit:
      name: limit
      description: limit number of results
      in: query
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 100
    product_id:
      name: product_id
      description: products Unique identifier
      in: path
      required: true
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]+$
    product_type:
      name: product_type
      description: type of product
      in: query
      required: true
      schema:
        type: string
        pattern: ^[a-zA-Z0-9-]+$
    product_availabilty:
      name: product_availabilty
      description: products availability
      in: path
      required: true
      schema:
        type: boolean
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
    ReturnProducts:
      description: Return products
      content:
        application/json:
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Auth
      in: header
      x-apikeyInfoFunc: main.apikey_auth
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: jwtdecoder.decode_token
  schemas:
    Message:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: message
          example: "success"
    Product:
      type: object
      required:
        - product_id
        - product_name
        - product_price
        - product_description
        - product_type
        - product_status
      properties:
        product_id:
          type: string
          description: Unique identifier
          example: "12"
        product_type:
          type: string
          description: product type
          example: "clothing"
        product_name:
          type: string
          description: product name
          example: "t-shirt"
        product_status:
          type: string
          description: product availability
          example: "available"
        product_price:
          type: number
          description: price of product
          example: 100.22
          minLength: 1
        product_description:
          type: string
          description: product description
        created:
          type: string
          format: date-time
          description: Creation time
          example: 2015-07-07T15:49:51.230+02:00
          readOnly: true
    User:
      type: object
      required:
        - first_name
        - last_name
        - username
        - dob
        - state
        - postcode
      properties:
        first_name:
          type: string
          description: first name
          example: "Adam"
        last_name:
          type: string
          description: last name
          example: "Powers"
        username:
          type: string
          description: username
          example: "adamnpowers"
          readOnly: true
        dob:
          type: string
          format: date
          description: date of birth
          example: "2000-01-05"
        state:
          type: string
          description: state
          example: "Texas"
        postcode:
          type: string
          description: postal code
          example: "D08TY32"
    Cart:
      type: object
      required:
        - product_id
        - no_of_items
      properties:
        no_of_items:
          type: integer
          description: number of items
          example: 3
        product_id:
          type: string
          description: product ID
          pattern: ^[a-zA-Z0-9-]+$
